[workspace]
members = [
    "crates/landmass",
    "crates/bevy_landmass",
    "crates/landmass_rerecast",
]
resolver = "2"

[patch.crates-io]
dodgy_2d = { git = "https://github.com/andriyDev/dodgy", branch = "dependabot/cargo/glam-0.32.0" }
wgpu             = { git = "https://github.com/slyedoc/wgpu.git", branch = "solari-rt-naga" }
wgpu-core        = { git = "https://github.com/slyedoc/wgpu.git", branch = "solari-rt-naga" }
wgpu-hal         = { git = "https://github.com/slyedoc/wgpu.git", branch = "solari-rt-naga" }
wgpu-types       = { git = "https://github.com/slyedoc/wgpu.git", branch = "solari-rt-naga" }
wgpu-naga-bridge = { git = "https://github.com/slyedoc/wgpu.git", branch = "solari-rt-naga" }
naga             = { git = "https://github.com/slyedoc/wgpu.git", branch = "solari-rt-naga" }
naga_oil         = { git = "https://github.com/slyedoc/naga_oil.git", branch = "solari-ser" }
ash              = { git = "https://github.com/ash-rs/ash.git", branch = "master" }
gpu-allocator    = { git = "https://github.com/slyedoc/gpu-allocator.git", branch = "ash-push-rename" }

[patch."https://github.com/bevyengine/bevy"]
bevy = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_a11y = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_animation = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_anti_alias = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_app = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_asset = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_camera = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_color = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_core_pipeline = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_derive = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_diagnostic = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_ecs = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_feathers = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_gilrs = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_gizmos = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_gizmos_render = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_gltf = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_image = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_input = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_input_focus = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_internal = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_light = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_log = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_material = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_math = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_mesh = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_pbr = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_picking = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_platform = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_post_process = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_ptr = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_reflect = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
#bevy_remote = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_render = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_scene = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_shader = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_sprite = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_sprite_render = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_state = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_tasks = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_text = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_time = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_transform = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_ui = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_ui_render = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_ui_widgets = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_utils = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_window = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
bevy_winit = { git = "https://github.com/slyedoc/bevy", branch = "solari-rt-pipeline" }
